name: "OPDS"
guid: "F30880AE-3365-449E-B9E6-BF133C8401B0"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-opds.png"
version: 7
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Provides an OPDS book feed"
description: >
  Provides an OPDS feed for book browsing.

category: "Books"
artifacts:
  - "Jellyfin.Plugin.Opds.dll"
changelog: |-
  - Jellyfin 10.11 support (#48) @crobibero
